server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

  #GMail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: oatuhtest2002@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
